# -*- coding: utf-8 -*-
"""PERCEPTRON_FRUTAS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FvmTI3faJAtkj8Q8XWSX_ZhYzWYTAz7E
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np

#from matplotlib import pyplot as plt
from matplotlib import pylab as plt

from ClassPerceptron import Perceptron

# Leer FrutasTrain.csv
datos = pd.read_csv("FrutasTrain.csv")
nColum = list(datos.columns.values)
print(nColum)

#--- DATOS DE ENTRENAMIENTO ---
X = np.array(datos.iloc[:,0:2])

#--- SALIDA BINARIA ---
T = datos['Clase'] == 'Melon'  #es boolean
T = np.array(T * 1)  #lo convierte en binario

ppn = Perceptron(alpha=0.1, n_iter=350, draw=1, title=nColum, random_state=None)
ppn.fit(X, T)

plt.plot(range(1, len(ppn.errors_) + 1), ppn.errors_, marker='o')
plt.xlabel('Iteraciones')
plt.ylabel('Cantidad de actualizaciones')
plt.show()

from PlotRegiones import plot_decision_regions

plot_decision_regions(X, T, classifier=ppn)
plt.xlabel(ppn.title[0])
plt.ylabel(ppn.title[1])
plt.legend(loc='lower left')
plt.show()

Y = ppn.predict(X)
print("Y = ", Y)
print("T = ", T)
aciertos = sum(Y == T)
print("aciertos = ", aciertos)
nAciertos = sum(Y==T)
print("%% de aciertos = %.2f %%" % (100*nAciertos/X.shape[0]))